version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS:


